# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94cbdbc10fb9c45964f2e0e87caf2be4a7b26a54775e3c1e29e164f1382003f6fc84d9702d26f99a555fa76af8a8bed89d096a022a4ade22160867702b99c484

test:
  secret_key_base: 16f0a0d2b01796c85706d49d7493908a64160399f1f681f42ee7ac0c91c7e4a51029c6e48aabb3878d4e1f1cf46b20977a83b2143e0b76cc243c0eec65f806b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
